name: Build and Deploy Laravel

on:
  push:
    branches:
      - main # Ubah ke 'master' jika branch Anda bernama master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4' # Diperbarui ke 8.4 karena error composer requires >= 8.4.1

    - name: Install Composer Dependencies
      run: composer install --optimize-autoloader --no-dev --no-interaction --prefer-dist

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install NPM Dependencies & Build Assets
      run: |
        npm install
        npm run build

    - name: Deploy to Hostdata via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./ # Karena akun FTP sudah diarahkan ke public_html/hotel/ di cPanel
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
          .env.example
          README.md
